version: '3'
services:
  apache:

    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - mariadb
    environment:
      WWWUSER: '${WWWUSER}'
    container_name: 'apache'
    volumes:
      - '.:/var/www/html/marketplace'
    networks:
      - apache
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  mariadb:
    image: 'mysql:8.0.31'
    ports:
      - '33061:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'yousef'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'marketplace'
      MYSQL_USER: 'yousef'
      MYSQL_PASSWORD: 'yousef'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb:/var/lib/mysql'
    networks:
      - apache
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-pyousef" ]
      retries: 3
      timeout: 5s

  redis:
    image: 'redis:latest'
    container_name: 'marketplaceRedis'
    restart: unless-stopped
    tty: true
#    command: >
#      --requirepass ${REDIS_PASSWORD:-yousef}
    ports:
      - '63792:6379'
    volumes:
      - 'redis:/data'
    networks:
      - apache

networks:
  apache:
    driver: bridge
volumes:
  mariadb:
    driver: local
  redis:
    driver: local